function [fitresult, gof] = createFit(omega, p)
%CREATEFIT(OMEGA,P)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: omega
%      Y Output: p
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Dec-2023 09:48:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( omega, p );

% Set up fittype and options.
ft = fittype( 'poly3' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Lower = [-Inf -Inf 0 0];
opts.Upper = [Inf Inf Inf 0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'p vs. omega', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'omega', 'Interpreter', 'none' );
ylabel( 'p', 'Interpreter', 'none' );
grid on


