function Simulation_Plot(x,Ts)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
t = linspace(0,size(x,2)*Ts,size(x,2));

figure()
subplot(2,1,1)
plot(t,x(1,:)')
ylabel("Velocity [m/s]")
legend("$\dot{x}$",'Interpreter', 'latex')
subplot(2,1,2)
plot(t,x(7,:)')
ylabel("Displacement [m]")
legend("$x$",'Interpreter', 'latex')
xlabel("Time [s]")

figure()
subplot(2,1,1)
plot(t,x(2,:)')
ylabel("Velocity [m/s]")
legend("$\dot{y}$",'Interpreter', 'latex')
subplot(2,1,2)
plot(t,x(8,:)')
ylabel("Displacement [m]")
legend("$y$",'Interpreter', 'latex')
xlabel("Time [s]")

figure()
subplot(2,1,1)
plot(t,x(3,:)')
ylabel("Velocity [m/s]")
legend("$\dot{z}$",'Interpreter', 'latex')
subplot(2,1,2)
plot(t,x(9,:)')
ylabel("Displacement [m]")
legend("$z$",'Interpreter', 'latex')
xlabel("Time [s]")

figure()
subplot(2,1,1)
plot(t,x(4,:)')
ylabel("Angular velocity [rad/s]")
legend("$\dot{\theta}$",'Interpreter', 'latex')
subplot(2,1,2)
plot(t,x(10,:)')
ylabel("Angle [rad]")
legend("$\theta$",'Interpreter', 'latex')
xlabel("Time [s]")

figure()
subplot(2,1,1)
plot(t,x(5,:)')
ylabel("Angular velocity [rad/s]")
legend("$\dot{\phi}$",'Interpreter', 'latex')
subplot(2,1,2)
plot(t,x(11,:)')
ylabel("Angle [rad]")
legend("$\phi$",'Interpreter', 'latex')
xlabel("Time [s]")

figure()
subplot(2,1,1)
plot(t,x(6,:)')
ylabel("Angular velocity [rad/s]")
legend("$\dot{\psi}$",'Interpreter', 'latex')
subplot(2,1,2)
plot(t,x(12,:)')
ylabel("Angle [rad]")
legend("$\psi$",'Interpreter', 'latex')
xlabel("Time [s]")


end